// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwCHIx8ZfRVn-nhc8RhAFd_Dju99salWc',
    appId: '1:276358087558:android:53e34b2c37d046006f6207',
    messagingSenderId: '276358087558',
    projectId: 'sturdy-now-380610',
    databaseURL: 'https://sturdy-now-380610-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sturdy-now-380610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz0z-vlFE1rWWC7V6CJDxD-uFzOPvy7dI',
    appId: '1:276358087558:ios:47a4408dd697513c6f6207',
    messagingSenderId: '276358087558',
    projectId: 'sturdy-now-380610',
    databaseURL: 'https://sturdy-now-380610-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sturdy-now-380610.appspot.com',
    iosClientId: '276358087558-dum2uhn8losbni3uge2979gg6op0qfej.apps.googleusercontent.com',
    iosBundleId: 'com.diviction.divictionCounselor',
  );
}
